### ISSUE TITLE
Cant build project

### ISSUE THREAD

**Issue by sp00ks-git** [waawaa/AMSI_Rubeus_bypass#1]
Hi,

I've tried building in x86 / x64 with either Debug and release versions and get the same whack of errors everytime.

Is there something im missing?
Microsoft Visual Studio Community 2019 Version 16.11.16
Microsoft Visual Studio Community 2019
Version 16.11.16
VisualStudio.16.Release/16.11.16+32602.291
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2019   00435-00000-00000-AA127
Microsoft Visual C++ 2019

.NET Core Debugging with WSL   1.0
.NET Core Debugging with WSL

ASP.NET and Web Tools 2019   16.11.106.23128
ASP.NET and Web Tools 2019

ASP.NET Web Frameworks and Tools 2019   16.11.106.23128
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   16.11.106.23128
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   16.11.106.23128
Azure Functions and Web Jobs Tools

C# Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Dotfuscator Community Edition   6.3.0+8b29d6f4a2
PreEmptive Protection - Dotfuscator CE

IncrediBuild Build Acceleration   1.5.0.13
IncrediBuild effectively reduces compilation and development times by up to 90%.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft Continuous Delivery Tools for Visual Studio   0.4
Simplifying the configuration of Azure DevOps pipelines from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft Library Manager   2.1.113+g422d40002e.RR
Install client-side libraries easily to any web project

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio Tools for Containers   1.2
Develop, run, validate your ASP.NET Core applications in the target environment. F5 your application directly into a container with debugging, or CTRL + F5 to edit & refresh your app without having to rebuild the container.

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.11.2
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Razor (ASP.NET Core)   16.1.0.2122504+13c05c96ea6bdbe550bd88b0bf6cdddf8cde1725
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   16.0.62205.05200
Microsoft SQL Server Data Tools

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30526.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.11.0-4.22108.8+d9bef045c4362fbcab27ef35daec4e95c8ff47e1
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.11.0-beta.21514.6+b6c2c4f53ea3a08fa603ea93d6d2f808a62a21d1
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers
===============================================================================

Rebuild started...
1>------ Rebuild All started: Project: Openssl-Dev, Configuration: Release x64 ------
1>cl : command line warning D9025: overriding '/MD' with '/MT'
1>sha256.cpp
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\sha256.cpp(125,61): warning C4267: 'argument': conversion from 'size_t' to 'unsigned int', possible loss of data
1>Source.cpp
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(2,1): warning C4005: '_MT': macro redefinition
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp : message : see previous definition of '_MT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(66,1): warning C4005: 'STATUS_WAIT_0': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2549): message : see previous definition of 'STATUS_WAIT_0'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(223,1): warning C4005: 'STATUS_ABANDONED_WAIT_0': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2550): message : see previous definition of 'STATUS_ABANDONED_WAIT_0'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(246,1): warning C4005: 'STATUS_USER_APC': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2551): message : see previous definition of 'STATUS_USER_APC'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(282,1): warning C4005: 'STATUS_TIMEOUT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2552): message : see previous definition of 'STATUS_TIMEOUT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(291,1): warning C4005: 'STATUS_PENDING': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2553): message : see previous definition of 'STATUS_PENDING'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(738,1): warning C4005: 'DBG_EXCEPTION_HANDLED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2554): message : see previous definition of 'DBG_EXCEPTION_HANDLED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(747,1): warning C4005: 'DBG_CONTINUE': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2555): message : see previous definition of 'DBG_CONTINUE'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(822,1): warning C4005: 'STATUS_SEGMENT_NOTIFICATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2556): message : see previous definition of 'STATUS_SEGMENT_NOTIFICATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(985,1): warning C4005: 'STATUS_FATAL_APP_EXIT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2557): message : see previous definition of 'STATUS_FATAL_APP_EXIT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1323,1): warning C4005: 'DBG_REPLY_LATER': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2558): message : see previous definition of 'DBG_REPLY_LATER'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1341,1): warning C4005: 'DBG_TERMINATE_THREAD': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2559): message : see previous definition of 'DBG_TERMINATE_THREAD'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1350,1): warning C4005: 'DBG_TERMINATE_PROCESS': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2560): message : see previous definition of 'DBG_TERMINATE_PROCESS'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1359,1): warning C4005: 'DBG_CONTROL_C': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2561): message : see previous definition of 'DBG_CONTROL_C'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1368,1): warning C4005: 'DBG_PRINTEXCEPTION_C': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2562): message : see previous definition of 'DBG_PRINTEXCEPTION_C'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1377,1): warning C4005: 'DBG_RIPEXCEPTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2563): message : see previous definition of 'DBG_RIPEXCEPTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1386,1): warning C4005: 'DBG_CONTROL_BREAK': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2564): message : see previous definition of 'DBG_CONTROL_BREAK'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1395,1): warning C4005: 'DBG_COMMAND_EXCEPTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2565): message : see previous definition of 'DBG_COMMAND_EXCEPTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1404,1): warning C4005: 'DBG_PRINTEXCEPTION_WIDE_C': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2566): message : see previous definition of 'DBG_PRINTEXCEPTION_WIDE_C'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1436,1): warning C4005: 'STATUS_GUARD_PAGE_VIOLATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2567): message : see previous definition of 'STATUS_GUARD_PAGE_VIOLATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1447,1): warning C4005: 'STATUS_DATATYPE_MISALIGNMENT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2568): message : see previous definition of 'STATUS_DATATYPE_MISALIGNMENT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1458,1): warning C4005: 'STATUS_BREAKPOINT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2569): message : see previous definition of 'STATUS_BREAKPOINT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1469,1): warning C4005: 'STATUS_SINGLE_STEP': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2570): message : see previous definition of 'STATUS_SINGLE_STEP'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1772,1): warning C4005: 'STATUS_LONGJUMP': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2571): message : see previous definition of 'STATUS_LONGJUMP'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1799,1): warning C4005: 'STATUS_UNWIND_CONSOLIDATE': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2572): message : see previous definition of 'STATUS_UNWIND_CONSOLIDATE'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(1914,1): warning C4005: 'DBG_EXCEPTION_NOT_HANDLED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2573): message : see previous definition of 'DBG_EXCEPTION_NOT_HANDLED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2060,1): warning C4005: 'STATUS_ACCESS_VIOLATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2574): message : see previous definition of 'STATUS_ACCESS_VIOLATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2069,1): warning C4005: 'STATUS_IN_PAGE_ERROR': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2575): message : see previous definition of 'STATUS_IN_PAGE_ERROR'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2087,1): warning C4005: 'STATUS_INVALID_HANDLE': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2576): message : see previous definition of 'STATUS_INVALID_HANDLE'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2132,1): warning C4005: 'STATUS_INVALID_PARAMETER': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2577): message : see previous definition of 'STATUS_INVALID_PARAMETER'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2232,1): warning C4005: 'STATUS_NO_MEMORY': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2578): message : see previous definition of 'STATUS_NO_MEMORY'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2289,1): warning C4005: 'STATUS_ILLEGAL_INSTRUCTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2579): message : see previous definition of 'STATUS_ILLEGAL_INSTRUCTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2370,1): warning C4005: 'STATUS_NONCONTINUABLE_EXCEPTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2580): message : see previous definition of 'STATUS_NONCONTINUABLE_EXCEPTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(2379,1): warning C4005: 'STATUS_INVALID_DISPOSITION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2581): message : see previous definition of 'STATUS_INVALID_DISPOSITION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3312,1): warning C4005: 'STATUS_ARRAY_BOUNDS_EXCEEDED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2582): message : see previous definition of 'STATUS_ARRAY_BOUNDS_EXCEEDED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3322,1): warning C4005: 'STATUS_FLOAT_DENORMAL_OPERAND': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2583): message : see previous definition of 'STATUS_FLOAT_DENORMAL_OPERAND'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3332,1): warning C4005: 'STATUS_FLOAT_DIVIDE_BY_ZERO': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2584): message : see previous definition of 'STATUS_FLOAT_DIVIDE_BY_ZERO'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3342,1): warning C4005: 'STATUS_FLOAT_INEXACT_RESULT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2585): message : see previous definition of 'STATUS_FLOAT_INEXACT_RESULT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3352,1): warning C4005: 'STATUS_FLOAT_INVALID_OPERATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2586): message : see previous definition of 'STATUS_FLOAT_INVALID_OPERATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3362,1): warning C4005: 'STATUS_FLOAT_OVERFLOW': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2587): message : see previous definition of 'STATUS_FLOAT_OVERFLOW'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3372,1): warning C4005: 'STATUS_FLOAT_STACK_CHECK': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2588): message : see previous definition of 'STATUS_FLOAT_STACK_CHECK'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3382,1): warning C4005: 'STATUS_FLOAT_UNDERFLOW': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2589): message : see previous definition of 'STATUS_FLOAT_UNDERFLOW'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3392,1): warning C4005: 'STATUS_INTEGER_DIVIDE_BY_ZERO': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2590): message : see previous definition of 'STATUS_INTEGER_DIVIDE_BY_ZERO'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3402,1): warning C4005: 'STATUS_INTEGER_OVERFLOW': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2591): message : see previous definition of 'STATUS_INTEGER_OVERFLOW'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(3412,1): warning C4005: 'STATUS_PRIVILEGED_INSTRUCTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2592): message : see previous definition of 'STATUS_PRIVILEGED_INSTRUCTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(4358,1): warning C4005: 'STATUS_STACK_OVERFLOW': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2593): message : see previous definition of 'STATUS_STACK_OVERFLOW'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(4875,1): warning C4005: 'STATUS_DLL_NOT_FOUND': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2594): message : see previous definition of 'STATUS_DLL_NOT_FOUND'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(4904,1): warning C4005: 'STATUS_ORDINAL_NOT_FOUND': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2595): message : see previous definition of 'STATUS_ORDINAL_NOT_FOUND'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(4914,1): warning C4005: 'STATUS_ENTRYPOINT_NOT_FOUND': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2596): message : see previous definition of 'STATUS_ENTRYPOINT_NOT_FOUND'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(4924,1): warning C4005: 'STATUS_CONTROL_C_EXIT': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2597): message : see previous definition of 'STATUS_CONTROL_C_EXIT'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(5002,1): warning C4005: 'STATUS_DLL_INIT_FAILED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2598): message : see previous definition of 'STATUS_DLL_INIT_FAILED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(5999,1): warning C4005: 'STATUS_CONTROL_STACK_VIOLATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2599): message : see previous definition of 'STATUS_CONTROL_STACK_VIOLATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(7593,1): warning C4005: 'STATUS_FLOAT_MULTIPLE_FAULTS': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2600): message : see previous definition of 'STATUS_FLOAT_MULTIPLE_FAULTS'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(7603,1): warning C4005: 'STATUS_FLOAT_MULTIPLE_TRAPS': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2601): message : see previous definition of 'STATUS_FLOAT_MULTIPLE_TRAPS'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(7735,1): warning C4005: 'STATUS_REG_NAT_CONSUMPTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2602): message : see previous definition of 'STATUS_REG_NAT_CONSUMPTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(8718,1): warning C4005: 'STATUS_HEAP_CORRUPTION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2603): message : see previous definition of 'STATUS_HEAP_CORRUPTION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(8946,1): warning C4005: 'STATUS_STACK_BUFFER_OVERRUN': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2604): message : see previous definition of 'STATUS_STACK_BUFFER_OVERRUN'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(9073,1): warning C4005: 'STATUS_INVALID_CRUNTIME_PARAMETER': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2605): message : see previous definition of 'STATUS_INVALID_CRUNTIME_PARAMETER'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(9136,1): warning C4005: 'STATUS_ASSERTION_FAILURE': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2606): message : see previous definition of 'STATUS_ASSERTION_FAILURE'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(10045,1): warning C4005: 'STATUS_ENCLAVE_VIOLATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2607): message : see previous definition of 'STATUS_ENCLAVE_VIOLATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(10688,1): warning C4005: 'STATUS_INTERRUPTED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2608): message : see previous definition of 'STATUS_INTERRUPTED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(10697,1): warning C4005: 'STATUS_THREAD_NOT_RUNNING': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2609): message : see previous definition of 'STATUS_THREAD_NOT_RUNNING'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(11000,1): warning C4005: 'STATUS_ALREADY_REGISTERED': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2610): message : see previous definition of 'STATUS_ALREADY_REGISTERED'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(14829,1): warning C4005: 'STATUS_SXS_EARLY_DEACTIVATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2612): message : see previous definition of 'STATUS_SXS_EARLY_DEACTIVATION'
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\shared\ntstatus.h(14838,1): warning C4005: 'STATUS_SXS_INVALID_DEACTIVATION': macro redefinition
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.22000.0\um\winnt.h(2613): message : see previous definition of 'STATUS_SXS_INVALID_DEACTIVATION'
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(85,5): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(177,8): warning C4838: conversion from 'int' to 'char' requires a narrowing conversion
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(177,8): warning C4309: 'initializing': truncation of constant value
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(178,8): warning C4838: conversion from 'int' to 'char' requires a narrowing conversion
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(178,8): warning C4309: 'initializing': truncation of constant value
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(178,14): warning C4838: conversion from 'int' to 'char' requires a narrowing conversion
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(178,14): warning C4309: 'initializing': truncation of constant value
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(215,34): warning C4018: '<': signed/unsigned mismatch
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(224,2): error C3861: 'restore_hook_ntcreatesection': identifier not found
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(233,2): error C2065: 'myNtCreateSection': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(233,20): error C2146: syntax error: missing ';' before identifier 'NtCreate'
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(233,20): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(234,2): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(234,14): error C2065: 'myNtCreateSection': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(234,32): error C2146: syntax error: missing ';' before identifier 'GetProcAddress'
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(238,17): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(238,34): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(241,33): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(245,2): error C3861: 'NtCreate': identifier not found
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(246,2): error C3861: 'hook_ntcreatesection': identifier not found
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(254,2): error C2065: 'myNtCreateSection': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(254,20): error C2146: syntax error: missing ';' before identifier 'NtCreate'
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(254,20): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(255,2): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(255,14): error C2065: 'myNtCreateSection': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(255,32): error C2146: syntax error: missing ';' before identifier 'GetProcAddress'
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(256,7): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(261,17): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(261,34): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(266,36): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(274,42): error C2065: 'NtCreate': undeclared identifier
1>C:\Scripts\AMSI_Rubeus_bypass\Openssl-Dev\Source.cpp(313,82): warning C4267: 'argument': conversion from 'size_t' to 'DWORD', possible loss of data
1>Done building project "Openssl-Dev.vcxproj" -- FAILED.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by waawaa** [comment]
myNtCreateSection definition was missing (it was copied from a bigger code, and i didn´t copy that def), solved now.

**Comment by sp00ks-git** [comment]
Working now, thanks.
